---
- name: Deploy InfluxDB Docker container.
  community.docker.docker_container:
    name: InfluxDB
    image: influxdb:2.6.1-alpine
    ports:
      - "8086:8086"
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    restart_policy: false
