---
- name: Deploy telegraf Docker container.
  community.docker.docker_container:
    name: Telegraf
    image: telegraf:alpine
    volumes:
      - "{{ config_path }}/telegraf/:/etc/telegraf/:ro"
    restart_policy: false
    env_file: "{{ config_path }}/.env"

- name: Install telegraf telegraf_packages.sh
  ansible.builtin.script:
    cmd: "{{ role_path }}/files/telegraf_packages.sh"

- name: Ensure speedtest is installed.
  ansible.builtin.cron:
    name: "install telegraf packages"
    minute: "0"
    hour: "*/6"
    job: "/bin/bash {{ config_path }}/telegraf_packages.sh > /dev/null"
