---
- name: Homelab configuration
  hosts: homelabs

  vars_files:
    - vars/system_vars.yml
    - vars/secret_vars.yml

  roles:
    - role: ubuntu_base
      tags: ['base']
    - role: docker_setup
      tags: ['docker_setup']
    - role: fiveetools_docker
      tags: ['5etools_docker']
    - role: heimdall_docker
      tags: ['heimdall']
    - role: plex_docker
      tags: ['plex_docker']
    - role: uptime_kuma_docker
      tags: ['uptime_kuma']
    - role: arr_stack_docker
      tags: ['arr_matey']
    - role: pi_alert_docker
      tags: ['pi_alert']
    - role: homer_docker
      tags: ['homer']

  tasks:
    - name: Reboot VM
      ansible.builtin.import_tasks: tasks/reboot.yml
      tags: ['never', 'reboot']
