---
- name: Homelab configuration
  hosts: homelabs

  vars_files:
    - vars/system_vars.yml
    - vars/secret_vars.yml

  roles:
    - role: roles/ubuntu_base
      tags: ['base']
    - role: roles/docker_setup
      tags: ['docker_setup']
    - role: roles/plex_docker
      tags: ['plex_docker']
    - role: roles/grafana_docker
      tags: ['grafana_docker']
    - role: roles/5etools_docker
      tags: ['5etools_docker']
    - role: roles/pihole_docker
      tags: ['pihole']
    - role: roles/heimdall_docker
      tags: ['heimdall']
    - role: roles/kavita_docker
      tags: ['kavita']

  tasks:
    - import_tasks: tasks/reboot.yml
      tags: ['never', 'reboot']
