---
- name: Homelab configuration
  hosts: homelabs

  vars_files:
    - vars/system_vars.yml
    - vars/secret_vars.yml

  roles:
    - role: ubuntu_base
      tags: ['base']
    - role: docker_setup
      tags: ['docker_setup']
    - role: grafana_docker
      tags: ['grafana_docker', 'monitoring']
    - role: 5etools_docker
      tags: ['5etools_docker']
    - role: pihole_docker
      tags: ['pihole']
    - role: heimdall_docker
      tags: ['heimdall']
    - role: kavita_docker
      tags: ['kavita']
    - role: prometheus_docker
      tags: ['prometheus', 'monitoring']
    - role: plex_docker
      tags: ['plex_docker']
    - role: plex_stat_explorer
      tags: ['plex_stats', 'monitoring']

  tasks:
    - name: Reboot VM
      ansible.builtin.import_tasks: tasks/reboot.yml
      tags: ['never', 'reboot']
