---
- name: Add users to docker group.
  ansible.builtin.user:
    name: "{{ username }}"
    groups: docker
    append: true
  become: true

- name: Reset ssh connection to apply user changes.
  ansible.builtin.meta: reset_connection
