---
- name: Deploy kavita Docker container.
  community.docker.docker_container:
    name: kavita
    image: kizaing/kavita:latest
    ports:
      - "5000:5000"
    volumes:
      - "{{ books_dir }}:/manga"
      - ./kavita_data:/kavita/config
    restart_policy: no
