---
- name: Install essential packages
  ansible.builtin.package:
    name: "{{ s. }}"
    state: latest
  become: true

- name: Install pip packages
  ansible.builtin.pip:
    name: "{{ pip_packages }}"

- name: Disable SSH password auth
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#PasswordAuthentication yes"
    line: "PasswordAuthentication no"
  become: true
  notify: Restart SSH daemon

- name: Change SSH port
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#Port 22"
    line: "Port {{ custom_ssh_port }}"
  become: true
  notify: Restart SSH daemon

- name: Enable passwordless sudo for "{{ username }}"
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "{{ username }} ALL=(ALL) NOPASSWD:ALL"
    validate: "/usr/sbin/visudo -cf %s"
  become: true
