---
- name: Deploy plex_stat_explorer Docker container.
  community.docker.docker_container:
    name: plex_stat_explorer
    image: ghcr.io/jsclayton/prometheus-plex-exporter
    ports:
      - "9001:9000/tcp"
    env:
      PLEX_SERVER: http://192.168.0.187:32400
      PLEX_TOKEN: "{{ plex_admin_token }}"
    restart_policy: false
