---
- name: Deploy qbittorent.
  ansible.builtin.include_tasks: qbittorrent-vpn.yml

- name: Deploy Jackett.
  ansible.builtin.include_tasks: jackett.yml

- name: Deploy Sonarr.
  ansible.builtin.include_tasks: sonarr.yml

- name: Deploy Radarr.
  ansible.builtin.include_tasks: radarr.yml

- name: Set up backup.
  ansible.builtin.include_tasks: backup.yml
